name = "Live Radio"
prefix = "live_radio"
author = "BrettMayson, Doble-K"
mainprefix = "z"

[files]
include = [
    "live_radio.dll",
    "live_radio_x64.dll",
    "logo_ca.paa",
    "logo_over_ca.paa",
    "picture_ca.paa"
]

[hemtt.launch]
workshop = [
    "450814997", # CBA
    "463939057", # ACE
]

[hemtt.launch.noace]
workshop = [
    "450814997", # CBA
]
