name: Arma

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_extension:
    strategy:
      matrix:
        arrays: [
          os: { tag: "windows-latest", target: "i686-pc-windows-msvc" },
          os: { tag: "windows-latest", target: "x86_64-pc-windows-msvc" },
        ]
    runs-on: ${{ matrix.arrays.os.tag }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Install latest
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arrays.os.target }}
      - name: Cargo Build
        run: cargo build --release
      - name: Upload
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.arrays.os.target }}
          path: target/release/live_radio.dll
          if-no-files-found: error
          retention-days: 30
  package:
    needs: build_extension
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/download-artifact@v5
        with:
          name: x86_64-pc-windows-msvc
      - run: mv live_radio.dll live_radio_x64.dll
      - uses: actions/download-artifact@v5
        with:
          name: i686-pc-windows-msvc
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Build
        run: hemtt release
      - uses: actions/upload-artifact@v5
        with:
          name: live_radio.zip
          path: 'releases/live_radio-latest.zip'
